In [ ]:
# Introduction to Numpy -----> 
# Numpy is an open-source library that is used for scintific calculations 

In [ ]:
# How Numpy is btter than List ? 
# (1). Numpy is homogeneous  data type while list is hetrogenous data type 
# (2). Numpy takes less memory while list take more memory  
# (3). Numpy take less execution time while List take more execution time

In [ ]:
!pip install numpy 

In [1]:
import numpy as np 

a = [1,45,78,90]
type(a) 
b = np.array(a) 
b

array([ 1, 45, 78, 90])

In [2]:
a = [] 
size = int(input("Enter size:"))
for i in range(size):
    val = int(input("Enter element:"))
    a.append(val) 
# print(a) 
b = np.array(a) 
b

Enter size: 4
Enter element: 12
Enter element: 34
Enter element: 56
Enter element: 15


array([12, 34, 56, 15])

In [3]:
type(b)

numpy.ndarray

In [4]:
a = [[1,2,3,4],[4,5,6,7],[7,8,9,5]]
a

[[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 5]]

In [5]:
b = np.array(a) 
b

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [7, 8, 9, 5]])

In [6]:
print("Total Rows and columns:" , b.shape)  ## shape = n(rows) , n(columns)
print("Total Elements:" , b.size)   ## size = total_elements = n(rows)*n(columns) 
print("Total Dimension:" , b.ndim) ##ndim stands for n_dimensional 

Total Rows and columns: (3, 4)
Total Elements: 12
Total Dimension: 2


In [ ]:
# Functions in Numpy

# (1). zeros() ----> It will create an array in which all the values in either one dimensional or 
# multi-dimensional will be 0

In [7]:
a = np.zeros(3) 
a

array([0., 0., 0.])

In [8]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# (2). ones() ----> It will crreate an array in which all the values will be 1 in either one 
# dimensional or multi-dimensional

In [9]:
a = np.ones(3) 
a

array([1., 1., 1.])

In [10]:
a = np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# (3). eye() -----> 
# Matrix ---> digonal Position ---> 1 
# It will create an array in which digonal positinoal elements will be 1 and rest all are 0

In [11]:
a = np.eye(3) 
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
a = np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
# (4). diag() ----> It will create an array in which you can set custom values at digonal position

In [13]:
a = np.diag([1,45,78,90])
a

array([[ 1,  0,  0,  0],
       [ 0, 45,  0,  0],
       [ 0,  0, 78,  0],
       [ 0,  0,  0, 90]])

In [ ]:
# (5). Random Module ----> It will return random numbers

In [ ]:
# (a). Randint() ----> It will return random numbers in a given range
# syntax: 
# np.random.randint(min_number ,max_number , total_numbers)

In [15]:
a = np.random.randint(1,10,3)
a

array([4, 7, 8], dtype=int32)

In [ ]:
# (b). rand() ---> It will provide random numbers in range of 0 to 1 

In [16]:
a = np.random.rand(4)
a

array([0.74401908, 0.75028839, 0.14930691, 0.97401399])

In [ ]:
# Random Numbers ---> data use ---> Output 
# if random numbers refresh update ---> previous output change

In [17]:
# (c). seed() ----> It will fix our random generated data 

np.random.seed(15) 
a = np.random.randint(1,10,3)
a

array([9, 6, 6], dtype=int32)

In [ ]:
# View and Copy

# view means modification in original data and copy means modification in duplicate data

In [18]:
a = np.array([10,20,30,40,50,60,70,80,90])
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [19]:
b = a[3:6]
b[:] = 0
b

array([0, 0, 0])

In [20]:
a

array([10, 20, 30,  0,  0,  0, 70, 80, 90])

In [21]:
a = np.array([10,20,30,40,50,60,70,80,90])
b = a[3:6].copy()
b[:] = 0
b

array([0, 0, 0])

In [23]:
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])